### ISSUE TITLE
Crash issue in createFromParcel(FluidSlider.kt:206)

### ISSUE THREAD

**Issue by AishwaryaNataraj** [Ramotion/fluid-slider-android#42]
Hi
Steps to reproduce

1. open the application
2. close it
3. click the stop button in logcat
4. open the application fragment crashes showing

Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: 
       at android.os.Parcel.readParcelableCreator(Parcel.java:2432)
       at android.os.Parcel.readParcelable(Parcel.java:2358)
       at android.view.AbsSavedState.<init>(AbsSavedState.java:57)
       at android.view.View$BaseSavedState.<init>(View.java:21500)
       _**at com.ramotion.fluidslider.FluidSlider$State.<init>(FluidSlider.kt:243)
       at com.ramotion.fluidslider.FluidSlider$State.<init>(FluidSlider.kt:202)
       at com.ramotion.fluidslider.FluidSlider$State$Companion$CREATOR$1.createFromParcel(FluidSlider.kt:207)
       at com.ramotion.fluidslider.FluidSlider$State$Companion$CREATOR$1.createFromParcel(FluidSlider.kt:206)
       at android.os.Parcel.readParcelable(Parcel.java:2367)**_
       at android.os.Parcel.readValue(Parcel.java:2264)
       at android.os.Parcel.readSparseArrayInternal(Parcel.java:2675)
       at android.os.Parcel.readSparseArray(Parcel.java:1967)
       at android.os.Parcel.readValue(Parcel.java:2321)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
       at android.os.BaseBundle.unparcel(BaseBundle.java:245)
       at android.os.Bundle.getSparseParcelableArray(Bundle.java:856)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1361)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
       at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3223)
       at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1526)
       at androidx.fragment.app.Fragment.onCreate(Fragment.java:1497)
       at com.daimler.busdetailspage.view.BusDetailFragment.onCreate(BusDetailFragment.java:101)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:2414)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
       at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3223)
       at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:190)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:369)
       at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
       at com.daimler.navigation.view.MainActivity.onCreate(MainActivity.java:165)
       at android.app.Activity.performCreate(Activity.java:6355)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2438)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2545)
       at android.app.ActivityThread.access$1100(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5601)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

**Comment by golovin47** [comment]
Hi, @AishwaryaNataraj. Couldn't reproduce this issue on any device. Usually that happens when you try to read from Parcel some custom class, but this lib writes/reads only Android Framework basic classes like Float, String etc. This issue is most probably related to the way you use this lib in your BusDetailFragment.
